name: Docker Angular Build - Final Project CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/angularbasic:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/angularbasic:latest

      - name: Clean up old container (if exists)
        run: |
          docker rm -f angularapp 2>$null -ErrorAction SilentlyContinue

      - name: Running container
        run: docker run -d -p 8080:80 --name angularapp ${{ secrets.DOCKER_USERNAME }}/angularbasic:latest

      - name: Wait for container to start
        run: timeout 30 bash -c "until curl -s http://localhost:8080 > /dev/null; do echo 'Waiting...'; sleep 2; done"

      - name: Test my container response
        run: |
          response=$(curl -s http://localhost:8080)
          echo "Response: $response"
          if [[ "$response" == *"Hello"* || "$response" == *"Angular"* ]]; then
            echo "Container responded successfully"
          else
            echo "Test failed: unexpected response"
            exit 1
          fi

      - name: Stop and remove container
        if: always()
        run: |
          docker stop angularapp -ErrorAction SilentlyContinue
          docker rm angularapp -ErrorAction SilentlyContinue
